### PR TITLE
Update CrosschainCoinRouter.sol

### PR DESCRIPTION
**Pull request by CrypticDriver**
Fix the bug that not require sender with value.

### CODE REVIEW

**Comment by CrypticDriver** [comment]
@guo Pls review it...

**Comment by guo** [comment]
Thanks for the submission! Could you please check out v0.2? V0.1 is a draft version and has been rewritten in v0.2.

**Comment by CrypticDriver** [comment]
@guo Thanks for your response, It seems the function is not yet implemented in V2 or probably deprecated.. 
@CoderZhi LGTM, I just a Cloud Engineer, your implementation looks more clever..

**Comment by guo** [comment]
All the smart contracts in this repo have not been deployed yet. And V0.2 is the version being worked on. V0.1 will be deprecated and kept here for information purposes. I appreciate if you can also look at v0.2.

Thanks!

**Comment by CrypticDriver** [comment]
@guo Sure...

**Review by CoderZhi — APPROVED** [review]

**Pull request merged**
